### ISSUE TITLE
docker-compose / testing purpose

### ISSUE THREAD

**Issue by ghost** [mingfang/diy-kubernetes#3]
Hi @mingfang ,

Hope you are all well !

Is it possible to create a docker-compose file to startup the master and worker/node ?

Here is what I have done so far 
```yaml
---
version: "3.8"
services:

  master:
    container_name: master-a
    build:
      context: ./master
    image: kubernetes-master
    stdin_open: true
    tty: true
    privileged: true
    networks:
    - internal
    - web
    ports:
    - 6443:6443
    depends_on:
    - node

  node:
    build:
      context: ./node
    container_name: node-a
    image: kubernetes-node
    stdin_open: true
    tty: true
    privileged: true
    networks:
    - internal

networks:
  internal:
    driver: bridge
  web:
    external: true
```

Do you mind to complete as I struggle with it ?

Cheers,
X
